

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: NordicInsureAI_backend
    ports:
      - "8000:8000"
    volumes:
       - ./shared:/app/shared
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: NordicInsureAI_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./shared:/app/shared
    restart: always